name: Build and Deploy

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.7
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.6
      with:
        name: static-files
        path: |
          *.html
          *.css
          *.js
